defaults:
-
  scope:
    path: ""
  values:
    layout: default
    _options:
      content: &content_defaults
        uploads_dir: "uploads/:title"
        format: p h1 h2 h3 h4 h5 h6 div
         styles: /assets/css/theme.css
        undo: true
        redo: true
        left: text-left
        center: text-center
        right: text-right
        justify: justify-content-center
        bold: true
        italic: true
        underline: true
        strike: true
        subscript: false
        superscript: false
        blockquote: true
        table: true
        copyformatting: true
        removeformat: true
        numberedlist: true
        bulletedlist: true
        outdent: false
        indent: false
        image: true
        link: true
        embed: true
-
  scope:
    type: posts
  values:
    layout: bloglayout
    
_inputs:
  image-position:
    type: select
    options:
      values:
        - top
        - center
        - bottom
