- name: Mowing
  description: >-
    We use commercial grade mowers designed to give your yard a professional
    cut.
  image: /uploads/2139e633-c87d-49d8-b2fd-791b72b97226-1-105-c.jpeg
- name: Weed Trimming
  description: >-
    We use commercial grade weed trimmers to provide the finishing touches to
    your yard.
  image: /uploads/ac821b8b-c7e2-455b-a7e4-598723b34575-1-105-c.jpeg
- name: Edging And Blowing
  description: >-
    We use commercial edgers to create the fine lines you desire, and our
    commercial blowers are used to provide a quick and precise clean up.
  image: /uploads/8da9a065-eb99-426b-9336-9fca1ab6ad97-1-105-c.jpeg
- name: Pesticide Maintenance Of Weeds And Bugs
  description: >-
    All Around Lawn Service Inc. is licensed by the Louisiana Department of
    Agriculture & Forestry as a Commercial Pesticide Applicator.
  image: /uploads/06f1f2ee-cb9a-4172-8e6a-1047a0ceff33-1-105-c.jpeg
- name: Flower Bed Maintenance
  description: We will keep your flower beds maintained and well groomed.
  image: /uploads/8da9a065-eb99-426b-9336-9fca1ab6ad97-1-105-c.jpeg
- name: Washing Houses And Buildings
  description: We provide washing of residential and commercial, one story buildings.
  image: /uploads/d1986d81-b09a-498a-b0c1-85c87c17cf39-1-105-c.jpeg
